### ISSUE TITLE
F003 Autovacuum tuning, IO  

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-checkup#108]

**Comment by dmius** [comment]
@NikolayS  @Nastradamus  Как и что собирать для этой проверки?

**Comment by Nastradamus** [comment]
@NikolayS удаваиваю вопрос. Еще и estimate такой.

@ane4ka why it is in backlog?

**Comment by ane4ka** [comment]
в бэклоге, потому что так мы вместе решили на планировании спринта. Я ничего сама по своему усмотрению не перетаскиваю из incoming

**Comment by NikolayS** [comment]
What we collect here:
- all `autovacuum_***` settings
- during 1 minute (should this duration be configurable?? @Nastradamus), observe iotop's if available) output:
```
sudo iotop -o -d 5 -n 12 -k -b
```
(every 5 seconds, 12 cycles – 5*12=60, print stats in kilobytes, use non-interactive mode)

**Comment by Nastradamus** [comment]
@NikolayS I think it is complicated for now. If we hardcode a check which locks a whole health-check for a minute, it will slow-down our manual tests and auto-tests in the future.

**Comment by dmius** [comment]
@Nastradamus  @NikolayS  А здесь в каком фомате собирать данные iotop ?

**Comment by NikolayS** [comment]
@Nastradamus ok, agreed. Let's consider iotop analysis as a separate item in the list.

What we completely forgot here: `autovacuum_***` settings can be changed at table level (`ALTER TABLE ... `). we need to check each table and highlight any "local" settings.
