### ISSUE TITLE
A008 Free disk space on disk partition with PGDATA - collect data

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-checkup#19]

**Comment by dmius** [comment]
df -h /usr/local/var/postgres
Filesystem     Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1  234Gi   79Gi  151Gi    35%  946464 9223372036853829343    0%   /

**Comment by dmius** [comment]
show data_directory

**Comment by Nastradamus** [comment]
```psql -c 'show data_directory'```

and then:

```df -h %data_dir_from_psql%```

**Comment by NikolayS** [comment]
PGDATA:
---
```
df -T $(psql -tAX -U postgres -c 'show data_directory')
```

Важно использовать опции у psql `-t`, `-A`, `-X` (хотя мы их, по идее, должны глобально использовать.

Насчет опции -h - не уверен, что нам надо ее тут задействовать, т.к., думаю, лучше взять количество байт в машиночитаемом виде, а дальше уже выводить в человекопонятном, когда надо (конвертируя в шаблоне, например). /cc @Nastradamus 

Дальше – как мы обсуждали, стоит забрать данные также и о всех разделах (просто `df -T`).

Также имеет смысл отдельно забрать данные по этим разделам, где сидят эти директории/файлы (важно, если оно вынесено на отдельные диски):

log_directory:
---
```
df -T $(psql -tAX -U postgres -c 'show log_directory')
```

stats_temp_directory:
---
```
df -T $(psql -tAX -U postgres -c 'show stats_temp_directory')
```

**Comment by Nastradamus** [comment]
@NikolayS мы хотим использовать в будущем враппер, который  будет определять через psql локальный или через ssh + psql ходить. Поэтому, лучше разделить вызов этих комманд.

**Comment by NikolayS** [comment]
обновил инструкции https://github.com/postgres-ai/postgres-health-check/issues/19#issuecomment-443135837
- добавил WAL dir
- разделил psql & df
