### ISSUE TITLE
D004 pg_stat_statements, tuning opts, _kcache - collect data

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-checkup#38]

**Comment by dmius** [comment]
@NikolayS  @Nastradamus  Как и что собирать для этой проверки?

**Comment by Nastradamus** [comment]
@dmius собрать какие настройки используют данные расширения (если есть).

**Comment by dmius** [comment]
@Nastradamus  А как это можно сделать, есть какие то запросы для этого?
