### ISSUE TITLE
G001 Memory-related settings - collect data

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-checkup#45]

**Comment by dmius** [comment]
@NikolayS  @Nastradamus  Что конкретно и как надо собрать в этом отчете?

**Comment by NikolayS** [comment]
- `max_connections`
- `work_mem`
- `maintenance_work_mem`
- `autovacuum_work_mem`
- `shared_buffers`
- `effective_cache_size`

**Comment by Nastradamus** [comment]
* temp_buffers

**Comment by dmius** [comment]
@Nastradamus  
> @ane4ka ane4ka added wontfix  S4  labels 11 days ago

**Comment by Nastradamus** [comment]
@ane4ka I deleted this label.

**Comment by dmius** [comment]
https://github.com/postgres-ai/postgres-health-check/pull/134
