### ISSUE TITLE
G003 Timeouts, locks, deadlocks (amount)

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-checkup#47]

**Comment by dmius** [comment]
@NikolayS  @Nastradamus  Как и что собирать для этой проверки?

**Comment by NikolayS** [comment]
Timeouts – get values for these settings:
- `statement_timeout` https://postgresqlco.nf/en/doc/param/statement_timeout
- `idle_in_transaction_session_timeout` https://postgresqlco.nf/en/doc/param/idle_in_transaction_session_timeout
- `authentication_timeout` https://postgresqlco.nf/en/doc/param/authentication_timeout

Locks and deadlocks
- `deadlock_timeout` https://postgresqlco.nf/en/doc/param/deadlock_timeout
- `lock_timeout` https://postgresqlco.nf/en/doc/param/lock_timeout
- `max_locks_per_transaction` https://postgresqlco.nf/en/doc/param/max_locks_per_transaction
- (only for versions 10+) `max_pred_locks_per_page` https://postgresqlco.nf/en/doc/param/max_pred_locks_per_page
- (only for versions 10+) `max_pred_locks_per_relation` https://postgresqlco.nf/en/doc/param/max_pred_locks_per_relation
- `max_pred_locks_per_transaction` https://postgresqlco.nf/en/doc/param/max_pred_locks_per_transaction 

Also get values `select conflicts, deadlocks, stats_reset from pg_stat_database where datname = ...` for each DB except `template0` and `template1`.

**Comment by Nastradamus** [comment]
> Also get values select conflicts, deadlocks, stats_reset from pg_stat_database where datname = ... for each DB except template0 and template1.

Yes, just iterate over all databases in the instance.

**Comment by dmius** [comment]
Добавить время с последнего ресета (postgres dba 0)
